# ~/.config/tmux/tmux.conf

# Préfixe & confort
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -sg escape-time 10

# Barre de statut en haut
set -g status-position top
set -g status-interval 30

set -g status-justify left
set -g status-style "bg=colour234,fg=white"

# Gauche : nom de session
set -g status-left "#[bold] #S "
set -g status-left-length 30

# Droite : DD/MM  HH:MM
set -g status-right "#[fg=cyan]%d/%m #[fg=yellow]%H:%M "
set -g status-right-length 20

# Fenêtres
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[bold,fg=green] #I:#W "

